--- #YAML:1.0
name:                Lyrics-Fetcher-LyricWiki
version:             0.04
abstract:            Get song lyrics from www.LyricWiki.org
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    SOAP::Lite:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Precious <davidp@preshweb.co.uk>
